### ISSUE TITLE
Add Bintray credentials to .travis.yml

### ISSUE THREAD

**Issue by knservis** [snowplow-incubator/snowplow-piinguin-relay#1]
Please fill in the secure credentials for bintray:
```
env:
  global:
  - secure: (BINTRAY_SNOWPLOW_GENERIC_API_KEY)
  - secure: (BINTRAY_SNOWPLOW_GENERIC_USER)
```

Here: https://github.com/snowplow-incubator/snowplow-piinguin-relay/blob/4f272fbce10a49e6344f51cfa87ba2aa295b24ef/.travis.yml#L20-L21
